apiVersion: v1
kind: Pod
metadata:
  name: no-toleration
  labels:
    purpose: "no-toleration"
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1f
  containers:
  - name: nginx
    image: nginx