apiVersion: v1
kind: Pod
metadata:
  name: no-az-toleration
  labels:
    purpose: "no-az-toleration-demo"
spec:
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoExecute" 